### ISSUE TITLE
Advanced Video Comparison

### ISSUE THREAD

**Issue by DonaldTsang** [thorn-oss/perception#10]
There have been proprietary apps like https://www.video-comparer.com/
The idea is: Given videos A and B, is it possible to match which parts of A aligns with which parts of B?
Also, it might be good to provide timestamps so that it can be input into MPV for close comparisons.

For other references: https://github.com/TorresAndy/4Hash/issues/2

There are forks of https://github.com/jonasob/blockhash/network that has such feature.
pHash already includes video hashing https://github.com/aetilius/pHash
There has been researches like https://github.com/rednoah/VASH and https://github.com/muesli/xray and https://github.com/kristiankoskimaki/vidupe and https://github.com/sschnug/pyVideoHash https://github.com/sschnug/pyVideoPartialCopyDetector and https://github.com/lsfxz/phidup and https://github.com/mediamicroservices/mm as well.

**Comment by faustomorales** [comment]
Hi @DonaldTsang -- We've just published v0.3.0 which includes more support for video hashing. 

- [Video hashing benchmarking](https://perception.thorn.engineering/en/v0.3.0/examples/benchmarking.html#video-hashing)
- [Enhanced video duplicate detection example](https://perception.thorn.engineering/en/v0.3.0/examples/deduplication.html#video-deduplication)

With respect to timestamps, the `SimpleSceneDetection` hasher wrapper now includes a `compute_batches` method which allows access to the timestamps for hashes.

Given that this issue is somewhat general and that video support has been expanded, what do you think about closing this issue in favor of separate, more granular issue(s)? Those issues could focus on specific hashing algorithms you find promising and for which you might want to consider contributing an implementation via a PR.

**Comment by DonaldTsang** [comment]
Thanks for the reply. It would be good from now on to dig through different papers to see if it is possible to have advanced video deduplication algorithms, as I am sure there are a lot of potential i that field. Contributions would be a great way to participate as well.
