### ISSUE TITLE
Questions regarding hash names

### ISSUE THREAD

**Issue by DonaldTsang** [thorn-oss/perception#4]
The names in https://github.com/knjcode/imgdupes#available-hash-algorithm are not the same in this repo, are they simply just the same algorithm with different name, or actually different algorithms not in the repo? If it is the latter, is it possible to add that to this repo?

**Comment by faustomorales** [comment]
All but one are the same but with different names. 

| imgdupes  | perception       |
|-----------|------------------|
| ahash     | AverageHash      |
| dhash     | DHash            |
| whash     | WaveletHash      |
| phash     | PHash            |
| phash_org | (see note below) |

For `phash_org`, `imgdupes` removes the first row and first column of the DCT computed for `PHash`. This means that an 8x8 pHash yields a hash vector of length 7x7 = 49. This is similar to `perception.hashers.PHash(exclude_first_term=True)` but in `perception` we remove only the first term so an 8x8 pHash yields a hash vector of length 63.

**Comment by DonaldTsang** [comment]
Okay would having phash_org and variants be a good idea?

**Comment by faustomorales** [comment]
First, allow me to correct myself -- re-reading the source in `imgdupes` I see that the slice they take retains the hash size (8x8) rather than reducing it. So the hash length remains 64.

Second, I ran a benchmark test with the variant and it looks as though it does improve performance in some cases (so thanks for suggesting this!). Here is the code I used to run the test. I've used the same benchmarking set as we describe in the [benchmarking example](https://perception.thorn.engineering/en/latest/examples/benchmarking.html).

```
import cv2
import scipy

from perception import benchmarking, hashers

class PHashOrg(hashers.PHash):
    def _compute_dct(self, image):
        img_size = self.hash_size * self.highfreq_factor
        image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
        image = cv2.resize(
            image, dsize=(img_size, img_size), interpolation=cv2.INTER_AREA)
        dct = scipy.fftpack.dct(scipy.fftpack.dct(image, axis=0), axis=1)
        return dct[1:self.hash_size+1, 1:self.hash_size+1]

transforms = benchmarking.BenchmarkTransforms.load('benchmarking_images', verify_md5=False)

hashes = transforms.compute_hashes(hashers={
    'phash_org': PHashOrg(hash_size=8),
    'phash_eft': hashers.PHash(hash_size=8, exclude_first_term=True),
    'phash': hashers.PHash(hash_size=8),
})
metrics_01 = hashes.compute_threshold_recall(fpr_threshold=1e-3, grouping=[])
metrics_001 = hashes.compute_threshold_recall(fpr_threshold=1e-4, grouping=[])
```

Below are the results at the 0.001 (0.1%) false positive rate threshold. The `phash_org` shows marked improvement at this threshold.

|           |   threshold |   recall |         fpr |   n_exemplars |
|-----------|-------------|----------|-------------|---------------|
| phash     |    0.125    |   65.493 | 9.43263e-05 |         38540 |
| phash_eft |    0.126984 |   65.493 | 9.43263e-05 |         38540 |
| phash_org |    0.15625  |   70.457 | 0.000202807 |         38540 |

Below are the results at the 0.0001 (0.01%) false positive rate threshold.

|           |   threshold |   recall |         fpr |   n_exemplars |
|-----------|-------------|----------|-------------|---------------|
| phash     |    0.125    |   65.493 | 9.43263e-05 |         38540 |
| phash_eft |    0.126984 |   65.493 | 9.43263e-05 |         38540 |
| phash_org |    0.125    |   63.954 | 0           |         38540 |

Because of the above results, I've added a frequency shift option to the `PHash` hasher so that one can obtain the `phash_org` behavior by using `perception.hashers.PHash(hash_size=8, freq_shift=1)`.

Please feel free to comment here or in the related PR (https://github.com/thorn-oss/perception/pull/5) which I'll plan to get reviewed next week after the Thanksgiving holiday.

**Comment by DonaldTsang** [comment]
Other comparisons I would like to note (but most of them are duplicates)
- https://github.com/corona10/goimagehash
- https://github.com/ameingast/cocoaimagehashing
- https://github.com/Nr90/imgsim
- https://github.com/Quickshot/DupImageLib

This one though is unique enough to warrant its own analysis https://github.com/KilianB/JImageHash

**Comment by faustomorales** [comment]
I perused the first four and those all look like they are accounted for in this package. As you suggested, the fifth package has some additional hash functions but the interesting ones all seem to me to be related to computing rotation-invariant hashes. Rotation invariance is indirectly the subject of https://github.com/thorn-oss/perception/issues/6 and so I would propose continuing the discussion of rotation invariance there. Let me know if you agree or disagree. Thanks!

**Comment by faustomorales** [comment]
This issue has been addressed by #5. The subject of rotation-invariant hashes continues in #6.

**Comment by DonaldTsang** [comment]
@faustomorales please update the ReadME to include wHash in https://github.com/thorn-oss/perception#supported-hashing-algorithms

**Comment by jacobwgillespie** [comment]
Submitted https://github.com/thorn-oss/perception/pull/7 to update README, @faustomorales feel free to edit if necessary.
